seed: 21
model_name: sentence-transformers/all-MiniLM-L6-v2
train_file: ./data/chunk_auto_labels.jsonl
valid_frac: 0.1
output_dir: ./outputs/chunk_classifier
max_length: 256
batch_size: 32
lr: 3.0e-5
epochs: 4
warmup_ratio: 0.1
label_list: [definition, theorem, rule, example, exercise]
mixed_precision: fp16
