seed: 42
model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
train_file: ./train/data/reranker_train.jsonl
valid_frac: 0.1
output_dir: ./train/outputs/reranker
max_length: 256
batch_size: 32
lr: 2.0e-5
epochs: 3
warmup_ratio: 0.1
eval_steps: 500
save_steps: 1000
mixed_precision: fp16
